### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by Seunadex** [Seunadex/chattie#3]
Models, Controller and the View needs refactoring.

**Comment by mikey2020** [comment]
@Seunadex Is this still needed ?

**Comment by Seunadex** [comment]
> @Seunadex Is this still needed ?

I've done some refactoring but you can still dive in and see what needs improvement.

**Comment by mikey2020** [comment]
Okay but if this has been done, cant this be closed

**Comment by Seunadex** [comment]
> Okay but if this has been done, cant this be closed

I believe this is a continuous improvement.
